const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {sealed}=require('./model.cjs'),m=require('./push-runner.cjs'),{encryptState,decryptState}=require('./runner.cjs');
async function tests(){let checks=0;const now=1791312000000,state={epoch:'test-epoch',events:[],pushLog:[]},recipient=await m.identity(state,now);assert.equal(recipient.key.d,undefined);const same=await m.identity(state,now+1);assert.equal(same.keyId,recipient.keyId);checks++;
const vapid=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),receiver=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),raw=new Uint8Array(await crypto.subtle.exportKey('raw',receiver.publicKey)),b64=a=>Buffer.from(a).toString('base64url'),endpoint='https://fcm.googleapis.com/fcm/send/local-test-only',id=require('node:crypto').createHash('sha256').update(endpoint).digest('hex'),config={format:'libi-push-config-v1',id:'local-config',subject:'https://libi-xau-gratis.libiliving.chatgpt.site',epoch:state.epoch,keyId:recipient.keyId,createdAt:now,expiresAt:now+86400000,vapidKey:await crypto.subtle.exportKey('jwk',vapid.privateKey),subscribers:[{id,subscribedAt:now-120000,subscription:{endpoint,expirationTime:null,keys:{p256dh:b64(raw),auth:b64(crypto.getRandomValues(new Uint8Array(16)))}}}]};await m.validateConfig(config,recipient,now);checks++;
for(const change of [{subject:'https://evil.example'},{epoch:'foreign'},{createdAt:now+60001},{expiresAt:now},{expiresAt:now+9*86400000},{subscribers:Array(11).fill(config.subscribers[0])},{subscribers:[config.subscribers[0],config.subscribers[0]]}]){await assert.rejects(()=>m.validateConfig({...config,...change},recipient,now));checks++;}
const envelope=await sealed.sealSnapshot(config,recipient.key);assert.equal(JSON.stringify(envelope).includes(endpoint),false);assert.equal(JSON.stringify(envelope).includes(config.vapidKey.d),false);const opened=await sealed.openSnapshot(envelope,state.pushIdentity.privateJwk);assert.equal(opened.id,config.id);checks++;
state.events=[{eventKey:'github:test:new',eventType:'NEW_SIGNAL',createdAt:now-60000,side:'BUY'},{eventKey:'github:test:old',eventType:'TP',createdAt:now-300001,side:'BUY'},{eventKey:'github:test:future',eventType:'TP',createdAt:now+1,side:'BUY'},{eventKey:'github:test:before-sub',eventType:'SL',createdAt:now-121000,side:'BUY'},{eventKey:'github:test:observation',eventType:'OBSERVATION',createdAt:now,side:'BUY'}];assert.equal(m.prepareClaims(state,config,now).length,1);assert.equal(m.prepareClaims(state,config,now).length,0);checks++;
const fresh={events:Array.from({length:15},(_,i)=>({eventKey:'github:test:'+i,eventType:'TP',createdAt:now,side:'BUY'}))};assert.equal(m.prepareClaims(fresh,config,now).length,6);checks++;const blocked={events:fresh.events,pushCooldownAt:now+60000};assert.equal(m.prepareClaims(blocked,config,now).length,0);checks++;
const root=fs.mkdtempSync(path.join(os.tmpdir(),'libi-push-test-')),secret='ephemeral-local-test-secret';process.env.LIBI_XAU_WAKE_SECRET=secret;try{const durable={...state,engineHash:'local-test',revision:1,status:'pending-entry',signalHash:null,side:null,payload:{},updatedAt:now,archives:[],runHistory:[{observedAt:now}],lastScan:null,dxy:null,pushClaims:{},pushLog:[]};fs.writeFileSync(path.join(root,'runner.json'),JSON.stringify(encryptState(durable,secret)));fs.writeFileSync(path.join(root,'push-config.json'),JSON.stringify({epoch:recipient.epoch,keyId:recipient.keyId,sealed:envelope}));await m.execute('prepare',{root,now,quiet:true});let persisted=decryptState(JSON.parse(fs.readFileSync(path.join(root,'runner.json'))),secret);assert.equal(persisted.pushQueue.length,1);assert.equal(persisted.pushLog[0].status,'delivery-unknown');assert.equal(fs.readFileSync(path.join(root,'runner.json'),'utf8').includes(endpoint),false);checks++;
let sent=0;await m.execute('send',{root,now,quiet:true,send:async()=>{sent++;return {accepted:true,expired:false,httpStatus:201,retryAfter:null};}});persisted=decryptState(JSON.parse(fs.readFileSync(path.join(root,'runner.json'))),secret);assert.equal(sent,1);assert.equal(persisted.pushLog[0].status,'accepted-by-service');assert.equal(persisted.pushQueue.length,0);checks++;
await m.execute('prepare',{root,now,quiet:true});await m.execute('send',{root,now,quiet:true,send:async()=>{sent++;throw Error('Must not resend');}});assert.equal(sent,1);checks++;
// Simulated interruption after durable claim: a whole workflow retry prepares zero duplicates.
persisted.events.push({eventKey:'github:test:interrupted',eventType:'SL',createdAt:now,side:'BUY'});fs.writeFileSync(path.join(root,'runner.json'),JSON.stringify(encryptState(persisted,secret)));await m.execute('prepare',{root,now,quiet:true});await m.execute('prepare',{root,now,quiet:true});await m.execute('send',{root,now,quiet:true,send:async()=>{throw Error('Must not resend ambiguous claim');}});persisted=decryptState(JSON.parse(fs.readFileSync(path.join(root,'runner.json'))),secret);assert.equal(persisted.pushLog.at(-1).status,'delivery-unknown');checks++;
}finally{fs.rmSync(root,{recursive:true,force:true});delete process.env.LIBI_XAU_WAKE_SECRET;}
console.log(JSON.stringify({sealedPushChecks:checks,failures:0,networkCalls:0,realDeviceDeliveryTested:false}));}
tests().catch(e=>{console.error(e.message);process.exitCode=1;});
