// Private configuration travels sealed to this runner. No Site access token is used.
const fs=require('node:fs'),path=require('node:path'),nodeCrypto=require('node:crypto');
const {sealed,push}=require('./model.cjs');
const {encryptState,decryptState}=require('./runner.cjs');
const siteKey=require('./site-public-key.json');
const SUBJECT='https://libi-xau-gratis.libiliving.chatgpt.site';
const labels={NEW_SIGNAL:'Nueva señal pendiente',ENTRY_REACHED:'Entrada observada',INVALIDATED:'Señal invalidada antes de entrada',TP:'TP observado',SL:'SL observado',AMBIGUOUS:'Resolución ambigua'};
const hash=s=>nodeCrypto.createHash('sha256').update(s).digest('hex');
function keyId(jwk){return hash(JSON.stringify({kty:jwk.kty,crv:jwk.crv,x:jwk.x,y:jwk.y}));}
async function identity(state,now){if(!state.pushIdentity){const pair=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);state.pushIdentity={privateJwk:await crypto.subtle.exportKey('jwk',pair.privateKey),publicJwk:await crypto.subtle.exportKey('jwk',pair.publicKey),createdAt:now};}return {format:'libi-push-recipient-v1',epoch:state.epoch,keyId:keyId(state.pushIdentity.publicJwk),key:state.pushIdentity.publicJwk,createdAt:state.pushIdentity.createdAt};}
async function validateConfig(config,recipient,now){if(config?.format!=='libi-push-config-v1'||config.subject!==SUBJECT||config.epoch!==recipient.epoch||config.keyId!==recipient.keyId||!Number.isFinite(config.createdAt)||config.createdAt>now+60000||config.expiresAt!==null&&(!Number.isFinite(config.expiresAt)||config.expiresAt<=now||config.expiresAt>config.createdAt+8*86400000)||!Array.isArray(config.subscribers)||config.subscribers.length>10||typeof config.id!=='string'||config.id.length>100)throw Error('Invalid or expired private delivery configuration');await crypto.subtle.importKey('jwk',config.vapidKey,{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const seen=new Set();for(const row of config.subscribers){const s=push.validateSubscription(row.subscription);if(row.id!==hash(s.endpoint)||seen.has(row.id)||!Number.isFinite(row.subscribedAt)||row.subscribedAt>config.createdAt||row.subscribedAt<0)throw Error('Invalid subscriber identity or time');seen.add(row.id);await crypto.subtle.importKey('raw',push.decode64(s.keys.p256dh),{name:'ECDH',namedCurve:'P-256'},false,[]);}return config;}
function prepareClaims(state,config,now){state.pushClaims??={};state.pushLog??=[];const queue=[];if(state.pushCooldownAt&&now<state.pushCooldownAt)return queue;for(const row of config.subscribers){if(state.expiredPushIds?.includes(row.id))continue;for(const e of state.events){if(!labels[e.eventType]||e.createdAt<row.subscribedAt||e.createdAt<now-300000||e.createdAt>now||queue.length>=6)continue;const id=hash(row.id+':'+e.eventKey);if(state.pushClaims[id])continue;const claim={id,deviceId:row.id,eventKey:e.eventKey,eventType:e.eventType,eventAt:e.createdAt,side:e.side,attemptedAt:now,status:'delivery-unknown',receivedAt:null};state.pushClaims[id]=true;state.pushLog.push(claim);queue.push(claim);}}state.pushLog=state.pushLog.slice(-500);return queue;}
function summary(state,config,now,error=null){return {mode:'github-sealed-push-v1',configured:!!config,configId:config?.id??null,expiresAt:config?.expiresAt??null,deviceIds:config?.subscribers.filter(s=>!state.expiredPushIds?.includes(s.id)).map(s=>s.id)??[],log:(state.pushLog??[]).slice(-500),checkedAt:now,error,receivedConfirmed:false};}
async function execute(mode,{root=process.env.LIBI_XAU_DATA_DIR||'state',now=Date.now(),send=push.sendWebPush,quiet=false}={}){const secret=process.env.LIBI_XAU_WAKE_SECRET;if(!secret||secret.length<16)throw Error('Encryption secret unavailable');const file=path.join(root,'runner.json'),state=decryptState(JSON.parse(fs.readFileSync(file,'utf8')),secret),recipient=await identity(state,now);let config=null,error=null;const configFile=path.join(root,'push-config.json');if(fs.existsSync(configFile))try{const envelope=JSON.parse(fs.readFileSync(configFile,'utf8'));if(envelope.keyId!==recipient.keyId||envelope.epoch!==recipient.epoch)throw Error('Different recipient');config=await validateConfig(await sealed.openSnapshot(envelope.sealed,state.pushIdentity.privateJwk),recipient,now);}catch{error='private-configuration-unavailable-or-expired';}
 if(mode==='prepare'){state.pushQueue=config?prepareClaims(state,config,now):[];state.pushConfigId=config?.id??null;}
 else if(mode==='send'){const queue=state.pushQueue??[];if(config&&state.pushConfigId===config.id)for(const claim of queue){if(claim.eventAt<now-300000||claim.eventAt>now||state.pushCooldownAt&&now<state.pushCooldownAt)continue;const row=config.subscribers.find(s=>s.id===claim.deviceId);if(!row||state.expiredPushIds?.includes(row.id))continue;try{const result=await send(row.subscription,{id:claim.id,title:'LiBi XAU · '+labels[claim.eventType],body:`${claim.side} · observación ${new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',timeStyle:'medium'}).format(claim.eventAt)}. Revisa niveles y frescura en la app.`,eventAt:claim.eventAt,url:'/',recordedAt:now},config.vapidKey,SUBJECT);Object.assign(claim,{status:result.accepted?'accepted-by-service':result.expired?'subscription-expired':'rejected-by-service',httpStatus:result.httpStatus});if(result.expired)state.expiredPushIds=[...new Set([...(state.expiredPushIds??[]),row.id])];if(result.httpStatus===429||result.httpStatus===503){const r=result.retryAfter,at=r&&/^\d+$/.test(r)?now+Number(r)*1000:r?Date.parse(r):NaN;state.pushCooldownAt=Math.max(now+60000,Number.isFinite(at)?at:0);} }catch{claim.status='delivery-unknown';}const index=state.pushLog.findIndex(e=>e.id===claim.id);if(index>=0)state.pushLog[index]={...claim};if(state.pushCooldownAt&&now<state.pushCooldownAt)break;}state.pushQueue=[];}
 else throw Error('Unknown delivery phase');
 state.pushSummary=summary(state,config,now,error);fs.writeFileSync(file,JSON.stringify(encryptState(state,secret)));fs.writeFileSync(path.join(root,'push-public.json'),JSON.stringify(recipient));
 // No private keys/subscriptions enter the Site mirror or job output.
 const mirror={format:'libi-xau-background-v1',engineHash:state.engineHash,epoch:state.epoch,revision:state.revision,status:state.status,signalHash:state.signalHash,side:state.side,payload:state.payload,updatedAt:state.updatedAt,lastScan:state.lastScan,events:state.events.slice(-500),eventsTruncated:state.events.length>500,archives:state.archives,runHistory:state.runHistory,quote:state.quote??null,dxy:state.dxy,observedAt:state.runHistory.at(-1)?.observedAt??now,push:state.pushSummary};fs.writeFileSync(path.join(root,'latest.json'),JSON.stringify(await sealed.sealSnapshot(mirror,siteKey)));if(!quiet)console.log(JSON.stringify({pushPhase:mode,configured:!!config,devices:state.pushSummary.deviceIds.length,claimed:(state.pushQueue??[]).length,accepted:(state.pushLog??[]).filter(e=>e.status==='accepted-by-service').length,error,receivedConfirmed:false}));return state.pushSummary;}
module.exports={identity,keyId,validateConfig,prepareClaims,summary,execute};if(require.main===module)execute(process.argv[2]).catch(()=>{console.error('Private push stage failed; details omitted, no credentials disclosed.');process.exitCode=1;});
