const fs=require('node:fs'),path=require('node:path'),cryptoNode=require('node:crypto');
const {engine,lifecycle,audit,macro,variants,feed,sealed}=require('./model.cjs');
const manifest=require('./source-manifest.json');
const publicKey=require('./site-public-key.json');
const hash=v=>cryptoNode.createHash('sha256').update(JSON.stringify(v)).digest('hex');
function encryptState(state,secret){const iv=cryptoNode.randomBytes(12),key=cryptoNode.createHash('sha256').update('libi-xau-runner-state-v1\0'+secret).digest(),cipher=cryptoNode.createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from('libi-xau-runner-state-v1'));const bytes=Buffer.concat([cipher.update(JSON.stringify(state)),cipher.final()]);return {format:'libi-xau-runner-state-v1',iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:bytes.toString('base64')};}
function decryptState(data,secret){if(data.format!=='libi-xau-runner-state-v1')throw Error('Unknown persisted state');const key=cryptoNode.createHash('sha256').update('libi-xau-runner-state-v1\0'+secret).digest(),dec=cryptoNode.createDecipheriv('aes-256-gcm',key,Buffer.from(data.iv,'base64'));dec.setAAD(Buffer.from('libi-xau-runner-state-v1'));dec.setAuthTag(Buffer.from(data.tag,'base64'));return JSON.parse(Buffer.concat([dec.update(Buffer.from(data.ciphertext,'base64')),dec.final()]).toString());}
function marketClosed(at){const n=new Date(at),d=n.getUTCDay(),h=n.getUTCHours();return d===6||d===0&&h<21||d===5&&h>=23;}
function evolve(state,calculation,observedAt,scanId){const signal=calculation.signal;let status=state.status,signalHash=state.signalHash,side=state.side,payload=state.payload,events=[];
 if((status==='pending-entry'||status==='triggered')&&payload.signal){const next=lifecycle.evaluateLifecycle(payload,status,calculation.audit.bars5,signal,observedAt,scanId);status=next.status;payload=next.payload;events=next.events;}
 else if((signal.side==='BUY'||signal.side==='SELL')&&signal.dataQuality?.ok!==false){status='pending-entry';signalHash='github:'+cryptoNode.randomUUID();side=signal.side;payload={signal,createdAt:observedAt,auditVersion:audit.AUDIT_VERSION,modelVersion:audit.MODEL_VERSION,lifecycleVersion:audit.LIFECYCLE_VERSION,scanId,lastScanAt:observedAt,flags:[],observations:0};events=[{eventType:'NEW_SIGNAL',eventKey:'NEW_SIGNAL',payload:{...payload,codeHash:manifest.originalEngineHash,trackingFrom:Math.ceil(observedAt/audit.BAR_MS)*audit.BAR_MS,brokerExecution:false}}];}
 const rows=events.map(e=>({eventKey:signalHash+':'+e.eventKey,eventType:e.eventType,signalHash,side,createdAt:observedAt,payload:e.payload})),known=new Set(state.events.map(e=>e.eventKey));return {...state,status,signalHash,side,payload,updatedAt:observedAt,events:[...state.events,...rows.filter(e=>!known.has(e.eventKey))],newEvents:rows.filter(e=>!known.has(e.eventKey))};}
async function run(){const secret=process.env.LIBI_XAU_WAKE_SECRET;if(!secret||secret.length<16)throw Error('Existing Actions encryption secret unavailable. No state is reset.');const root=process.env.LIBI_XAU_DATA_DIR||'state';fs.mkdirSync(root,{recursive:true});const filename=path.join(root,'runner.json'),now=Date.now();let state=fs.existsSync(filename)?decryptState(JSON.parse(fs.readFileSync(filename,'utf8')),secret):{format:'libi-xau-state-v1',engineHash:manifest.originalEngineHash,epoch:cryptoNode.randomUUID(),revision:0,status:'idle',signalHash:null,side:null,payload:{},updatedAt:0,events:[],archives:[],runHistory:[],dxy:null,lastScan:null};if(state.engineHash!==manifest.originalEngineHash)throw Error('Frozen engine identity changed. Manual review required.');
 const priorRun=state.runHistory.at(-1),runInfo={observedAt:now,runId:process.env.GITHUB_RUN_ID||'local',trigger:process.env.GITHUB_EVENT_NAME||'local',gapMs:priorRun?now-priorRun.observedAt:null,sourceCommit:process.env.GITHUB_SHA||null};let archive=null;
 try{
  if(marketClosed(now)){runInfo.status='market-closed';}
  else if(state.cooldownAt&&now<state.cooldownAt){runInfo.status='source-cooldown';}
  else{const [bars,ticks]=await Promise.all([feed.fetchBiquoteBars(),feed.fetchBiquoteTicks()]),at=Date.now();if(!state.dxy||at-state.dxy.observedAt>=1800000){const next=feed.biquoteDxy(ticks.raw,ticks.observedAt,state.dxy);if(next)state.dxy=next;}
   const calculation=engine.calculateFromBars(bars.bars,state.dxy,at);calculation.signal.source='biquote · XAUUSD de referencia MT5 · 5m + 15m agregado · DXY sintético';const context=macro.evaluateMacroRisk(at),scanId=hash({inputs:calculation.audit,decision:{...calculation.signal,timestamp:undefined},engineHash:manifest.originalEngineHash,macro:{knownAt:context.sourceObservedAt,status:context.status,version:context.version}});
   const duplicate=state.lastScan?.id===scanId;if(!duplicate){let comparisonStep=null;try{comparisonStep=variants.advanceComparison(state.comparison??null,variants.variantDecisions(calculation.signal,calculation.audit.bars5,calculation.audit.bars15,context,at),calculation.audit.bars5,at,scanId,hash(variants.PARALLEL_POLICY),()=>cryptoNode.randomUUID());}catch{runInfo.comparisonError="Independent trial preserved; parameters or input require review.";}state=evolve(state,calculation,at,scanId);if(comparisonStep)state.comparison=comparisonStep.state;archive={id:scanId,inputHash:scanId,observedAt:at,modelVersion:audit.MODEL_VERSION,payload:{auditVersion:audit.AUDIT_VERSION,modelVersion:audit.MODEL_VERSION,lifecycleVersion:audit.LIFECYCLE_VERSION,originalEngineHash:manifest.originalEngineHash,portVersion:manifest.version,parameters:audit.MODEL_POLICY,signal:calculation.signal,inputs:calculation.audit,sourceEvidence:{policy:feed.BIQUOTE_POLICY,instrument:bars.instrument,barResponse:bars.raw,barUrl:bars.url,barObservedAt:bars.observedAt,tickResponse:ticks.raw,tickUrl:ticks.url,tickObservedAt:ticks.observedAt,gaps:bars.gaps},macroContext:context,observedAt:at,origin:'github-actions',brokerExecution:false,comparisonPolicy:variants.PARALLEL_POLICY,newsDiagnostic:{independentStrategy:true,variant:'N0',mode:'parallel-calendar-risk',publicModelUnchanged:true},runInfo},comparison:comparisonStep?{...comparisonStep,codeHash:manifest.hashes["lib/xau/variants.ts"]}:null};
    state.lastScan={id:scanId,at,signal:calculation.signal,barAt:calculation.lastBarTimestamp,source:calculation.signal.source};}
   state.quote={price:ticks.tick.mid,providerAt:Date.parse(ticks.tick.timestamp),observedAt:ticks.observedAt,source:'biquote · referencia MT5',instrument:feed.BIQUOTE_POLICY.instrument,stale:false};runInfo.status=duplicate?'unchanged-input':state.status;runInfo.closedBarAt=bars.prepared.closedAt;runInfo.closedBarLatencyMs=at-bars.prepared.closedAt;runInfo.dataQuality=calculation.signal.dataQuality;
  }
 }catch(e){runInfo.status='source-error';runInfo.error=e.message;const r=e.retryAfter,parsed=r?(/^\d+$/.test(r)?Date.now()+Number(r)*1000:Date.parse(r)):NaN;state.cooldownAt=Math.max(Date.now()+60000,Number.isFinite(parsed)?parsed:0);}
 state.revision++;state.runHistory=[...state.runHistory,runInfo].slice(-500);if(archive){const file='archives/'+new Date(archive.observedAt).toISOString().slice(0,10)+'/'+state.revision+'.json';fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),JSON.stringify(await sealed.sealSnapshot({format:'libi-xau-archive-v1',epoch:state.epoch,revision:state.revision,archive,events:state.newEvents,comparison:archive.comparison},publicKey)));state.archives.push({path:file,id:archive.id,revision:state.revision});}delete state.newEvents;
 const latest={format:'libi-xau-background-v1',engineHash:state.engineHash,epoch:state.epoch,revision:state.revision,status:state.status,signalHash:state.signalHash,side:state.side,payload:state.payload,updatedAt:state.updatedAt,lastScan:state.lastScan,events:state.events.slice(-500),eventsTruncated:state.events.length>500,archives:state.archives,runHistory:state.runHistory,quote:state.quote??null,dxy:state.dxy,observedAt:Date.now(),comparison:state.comparison?{state:state.comparison,codeHash:manifest.hashes["lib/xau/variants.ts"]}:null};fs.writeFileSync(filename,JSON.stringify(encryptState(state,secret)));fs.writeFileSync(path.join(root,'latest.json'),JSON.stringify(await sealed.sealSnapshot(latest,publicKey)));console.log(JSON.stringify({revision:state.revision,status:runInfo.status,observedAt:runInfo.observedAt,gapMs:runInfo.gapMs,closedBarLatencyMs:runInfo.closedBarLatencyMs??null,encrypted:true,events:state.events.length,comparison:state.comparison?{trialId:state.comparison.trialId,revision:state.comparison.revision,startedAt:state.comparison.startedAt,policyHash:state.comparison.policyHash,codeHash:manifest.hashes["lib/xau/variants.ts"],statuses:Object.fromEntries(Object.entries(state.comparison.states).map(([id,s])=>[id,s.status]))}:null,comparisonError:runInfo.comparisonError??null}));return latest;
}
module.exports={run,evolve,encryptState,decryptState,marketClosed};if(require.main===module)run().catch(()=>{console.error('Runner failed before durable state update. Details omitted; state was not reset.');process.exitCode=1;});
