const assert=require('node:assert/strict'),cryptoNode=require('node:crypto');
const {feed,engine,sealed}=require('./model.cjs');const {encryptState,decryptState,evolve,marketClosed}=require('./runner.cjs');
async function tests(){let n=0;const now=Date.parse('2026-10-06T12:00:00Z'),bars=Array.from({length:120},(_,i)=>({openTime:new Date(now-(120-i)*300000).toISOString(),open:4100+i,high:4102+i,low:4099+i,close:4101+i,isOpen:false,volume:0,tickVolume:50})),env={symbol:'XAUUSD',interval:'5m',bars};assert.equal(feed.parseBiquoteBars(env,now).bars.length,120);n++;
 assert.throws(()=>feed.parseBiquoteBars({...env,symbol:'GC=F'},now));n++;assert.throws(()=>feed.parseBiquoteBars({...env,bars:[...bars,{...bars[0],close:4000}]},now));n++;assert.throws(()=>feed.parseBiquoteBars({...env,bars:[...bars,{...bars[0],openTime:'2026-10-06T12:05:00Z'}]},now));n++;
 const open={...bars.at(-1),openTime:new Date(now).toISOString(),isOpen:true};assert.equal(feed.parseBiquoteBars({...env,bars:[...bars,open]},now).openBars,1);n++;
 const ticks={};for(const [s,price] of Object.entries({EURUSD:1.1,USDJPY:150,GBPUSD:1.3,USDCAD:1.4,USDSEK:10,USDCHF:.85}))ticks[s]={symbol:s,bid:price-.00001,ask:price+.00001,mid:price,timestamp:new Date(now).toISOString(),source:'MT5',marketState:'open',stale:false};assert.equal(feed.biquoteDxy(ticks,now,null).previousDxy,null);n++;assert.equal(feed.biquoteDxy({...ticks,USDSEK:{...ticks.USDSEK,stale:true}},now,null),null);n++;
 const kp=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),pub=await crypto.subtle.exportKey('jwk',kp.publicKey),priv=await crypto.subtle.exportKey('jwk',kp.privateKey),box=await sealed.sealSnapshot({original:'retained'},pub);assert.deepEqual(await sealed.openSnapshot(box,priv),{original:'retained'});n++;await assert.rejects(()=>sealed.openSnapshot({...box,iv:box.iv.slice(0,-4)+'AAAA'},priv));n++;
 const persisted=encryptState({revision:42,payload:{entry:4200}},'test-only-not-production-secret');assert.deepEqual(decryptState(persisted,'test-only-not-production-secret'),{revision:42,payload:{entry:4200}});n++;assert.throws(()=>decryptState(persisted,'wrong-test-key'));n++;
 assert.equal(marketClosed(Date.parse('2026-10-10T12:00:00Z')),true);assert.equal(marketClosed(now),false);n++;
 const calculation=engine.calculateFromBars(feed.parseBiquoteBars(env,now).bars,null,now),base={status:'idle',signalHash:null,side:null,payload:{},events:[]};const next=evolve(base,calculation,now,'test-only-scan');assert.equal(next.status,'pending-entry');assert.equal(next.events[0].eventType,'NEW_SIGNAL');assert.equal(next.payload.signal.stop,calculation.signal.stop);n++;
 const again=evolve(next,{...calculation,signal:{...calculation.signal,stop:100,tp:200}},now+1000,'test-only-repeat');assert.equal(again.payload.signal.stop,next.payload.signal.stop);assert.equal(again.events.filter(e=>e.eventType==='NEW_SIGNAL').length,1);n++;
 console.log(JSON.stringify({background_checks:n,failures:0,scope:'Source gates, frozen plan, encryption integrity and closed-market guard; no production fixtures'}));}
module.exports=tests;if(require.main===module)tests().catch(e=>{console.error(e);process.exitCode=1;});
